<?php

// Route metadata keeps the app layout, access control, and menu data in one
// place so views do not need to know about every page by hand.
return [
  '/' => [
    'title' => 'Dashboard',
    'label' => 'Dashboard',
    'icon' => 'dashboard',
    'view' => __DIR__ . '/../views/pages/dashboard/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => false,
  ],
  '/dashboard' => [
    'title' => 'Dashboard',
    'label' => 'Dashboard',
    'icon' => 'dashboard',
    'group' => 'Overview',
    'view' => __DIR__ . '/../views/pages/dashboard/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/inventory' => [
    'title' => 'Inventory',
    'label' => 'Inventory',
    'icon' => 'inventory',
    'group' => 'Operations',
    'controller' => __DIR__ . '/../controllers/inventory/InventoryController.php',
    'class' => 'InventoryController',
    'method' => 'index',
    'view' => __DIR__ . '/../views/pages/inventory/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/inventory/save' => [
    'title' => 'Save inventory',
    'label' => 'Save inventory',
    'controller' => __DIR__ . '/../controllers/inventory/InventoryController.php',
    'class' => 'InventoryController',
    'method' => 'save',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => false,
  ],
  '/api/products' => [
    'title' => 'API Products',
    'label' => 'API Products',
    'controller' => __DIR__ . '/../controllers/inventory/InventoryController.php',
    'class' => 'InventoryController',
    'method' => 'getProductsJson',
    'layout' => 'none',
    'roles' => ['owner'],
    'show_in_nav' => false,
  ],
  '/products' => [
    'title' => 'Products',
    'label' => 'Products',
    'icon' => 'products',
    'group' => 'Operations',
    'view' => __DIR__ . '/../views/pages/products/index.php',
    'layout' => 'app',
    'roles' => ['owner', 'cashier'],
    'show_in_nav' => true,
  ],
  '/reports' => [
    'title' => 'Reports',
    'label' => 'Reports',
    'icon' => 'reports',
    'group' => 'Insights',
    'view' => __DIR__ . '/../views/pages/reports/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/suppliers' => [
    'title' => 'Suppliers',
    'label' => 'Suppliers',
    'icon' => 'suppliers',
    'group' => 'Operations',
    'view' => __DIR__ . '/../views/pages/suppliers/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/audit-logs' => [
    'title' => 'Audit logs',
    'label' => 'Audit logs',
    'icon' => 'audit-logs',
    'group' => 'Management',
    'view' => __DIR__ . '/../views/pages/audit-logs/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/audit-logs/personal' => [
    'title' => 'Personal audit logs',
    'label' => 'Audit logs',
    'icon' => 'audit-logs-personal',
    'group' => 'Management',
    'view' => __DIR__ . '/../views/pages/audit-logs/personal/index.php',
    'layout' => 'app',
    'roles' => ['cashier'],
    'show_in_nav' => true,
  ],
  '/users' => [
    'title' => 'Users',
    'label' => 'Users',
    'icon' => 'users',
    'group' => 'Management',
    'view' => __DIR__ . '/../views/pages/users/index.php',
    'layout' => 'app',
    'roles' => ['owner'],
    'show_in_nav' => true,
  ],
  '/sign-in' => [
    'title' => 'Sign in',
    'label' => 'Sign in',
    'icon' => 'sign-in',
    // The sign-in route runs a controller before the view so POST requests can
    // authenticate and redirect without mixing login logic into the template.
    'controller' => __DIR__ . '/../controllers/auth/AuthController.php',
    'class' => 'AuthController',
    'method' => 'signIn',
    'view' => __DIR__ . '/../views/pages/auth/sign-in.php',
    'layout' => 'auth',
    'roles' => ['guest'],
    'show_in_nav' => false,
  ],
  '/sign-out' => [
    'title' => 'Sign out',
    'label' => 'Sign out',
    'icon' => 'sign-out',
    'controller' => __DIR__ . '/../controllers/auth/AuthController.php',
    'class' => 'AuthController',
    'method' => 'signOut',
    'layout' => 'app',
    'roles' => ['owner', 'cashier'],
    'show_in_nav' => false,
  ],
  '/not-found' => [
    'title' => 'Not found',
    'label' => 'Not found',
    'icon' => 'not-found',
    'view' => __DIR__ . '/../views/pages/not-found.php',
    'layout' => 'auth',
    'roles' => ['owner', 'cashier', 'guest'],
    'show_in_nav' => false,
  ],
];
