<?php

declare(strict_types=1);

return [
  '/api/stock-in' => [
    'title' => 'Save stock-in',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/ProductsController.php',
    'class' => 'ProductsController',
    'method' => 'save',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/products' => [
    'title' => 'API Products',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/ProductsController.php',
    'class' => 'ProductsController',
    'method' => 'getProductsJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/products/list' => [
    'title' => 'API Products List',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/ProductsController.php',
    'class' => 'ProductsController',
    'method' => 'getProductsListJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/suppliers' => [
    'title' => 'API Suppliers',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/Suppliers/SuppliersController.php',
    'class' => 'SuppliersController',
    'method' => 'getSuppliersJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/suppliers/save' => [
    'title' => 'Save supplier',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/Suppliers/SuppliersController.php',
    'class' => 'SuppliersController',
    'method' => 'save',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/inventory/batches' => [
    'title' => 'Get batches',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'getBatchesJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/inventory/batches/count' => [
    'title' => 'Get batch count',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'getBatchCountJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/inventory/batches/detail' => [
    'title' => 'Get batch detail',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'getBatchJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/inventory/batches/update' => [
    'title' => 'Update batch',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'updateBatchJson',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/inventory/batches/void' => [
    'title' => 'Void batch',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'voidBatchJson',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/stock-out/batches' => [
    'title' => 'Get batches for dispatch',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/BatchController.php',
    'class' => 'BatchController',
    'method' => 'getBatchesForDispatchJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/stock-out' => [
    'title' => 'Submit dispatch',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/products/ProductsController.php',
    'class' => 'ProductsController',
    'method' => 'dispatch',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/users' => [
    'title' => 'API Users',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/users/UsersController.php',
    'class' => 'UsersController',
    'method' => 'getUsersJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/users/save' => [
    'title' => 'Save user',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/users/UsersController.php',
    'class' => 'UsersController',
    'method' => 'save',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/users/deactivate' => [
    'title' => 'Deactivate user',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/users/UsersController.php',
    'class' => 'UsersController',
    'method' => 'deactivate',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/supplier/save' => [
    'title' => 'Save supplier (legacy)',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/Suppliers/SuppliersController.php',
    'class' => 'SuppliersController',
    'method' => 'save',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/audit-logs' => [
    'title' => 'API Audit Logs',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/audit-logs/AuditLogsController.php',
    'class' => 'AuditLogsController',
    'method' => 'getLogsJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/audit-logs/personal' => [
    'title' => 'API Personal Audit Logs',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/audit-logs/AuditLogsController.php',
    'class' => 'AuditLogsController',
    'method' => 'getPersonalLogsJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['staff'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/dispatches/today' => [
    'title' => 'API Today Dispatches',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/dispatches/DispatchesController.php',
    'class' => 'DispatchesController',
    'method' => 'getTodayDispatchesJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'show' => false,
    ],
  ],
  '/api/dispatches/items' => [
    'title' => 'API Dispatch Items',
    'type' => 'api',
    'controller' => __DIR__ . '/../../controllers/dispatches/DispatchesController.php',
    'class' => 'DispatchesController',
    'method' => 'getDispatchItemsJson',
    'layout' => 'none',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'show' => false,
    ],
  ],
];
