<?php

declare(strict_types=1);

return [
  '/' => [
    'title' => 'Dashboard',
    'view' => __DIR__ . '/../../views/pages/dashboard/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Dashboard',
      'icon' => 'dashboard',
      'group' => 'Overview',
      'show' => false,
    ],
  ],
  '/dashboard' => [
    'title' => 'Dashboard',
    'view' => __DIR__ . '/../../views/pages/dashboard/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Dashboard',
      'icon' => 'dashboard',
      'group' => 'Overview',
      'show' => true,
    ],
  ],
  '/inventory' => [
    'title' => 'Inventory',
    'controller' => __DIR__ . '/../../controllers/products/ProductsController.php',
    'class' => 'ProductsController',
    'method' => 'index',
    'view' => __DIR__ . '/../../views/pages/inventory/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Inventory',
      'icon' => 'inventory',
      'group' => 'Operations',
      'show' => true,
    ],
  ],
  '/products' => [
    'title' => 'Products',
    'view' => __DIR__ . '/../../views/pages/products/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'label' => 'Products',
      'icon' => 'products',
      'group' => 'Operations',
      'show' => true,
    ],
  ],
  '/reports' => [
    'title' => 'Reports',
    'view' => __DIR__ . '/../../views/pages/reports/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Reports',
      'icon' => 'reports',
      'group' => 'Insights',
      'show' => true,
    ],
  ],
  '/suppliers' => [
    'title' => 'Suppliers',
    'view' => __DIR__ . '/../../views/pages/suppliers/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Suppliers',
      'icon' => 'suppliers',
      'group' => 'Operations',
      'show' => true,
    ],
  ],
  '/audit-logs' => [
    'title' => 'Audit logs',
    'view' => __DIR__ . '/../../views/pages/audit-logs/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Audit logs',
      'icon' => 'audit-logs',
      'group' => 'Management',
      'show' => true,
    ],
  ],
  '/audit-logs/personal' => [
    'title' => 'Personal audit logs',
    'view' => __DIR__ . '/../../views/pages/audit-logs/personal/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['staff'],
    'nav' => [
      'label' => 'Audit logs',
      'icon' => 'audit-logs-personal',
      'group' => 'Management',
      'show' => true,
    ],
  ],
  '/users' => [
    'title' => 'Users',
    'view' => __DIR__ . '/../../views/pages/users/index.php',
    'layout' => 'app',
    'methods' => ['GET'],
    'roles' => ['owner'],
    'nav' => [
      'label' => 'Users',
      'icon' => 'users',
      'group' => 'Management',
      'show' => true,
    ],
  ],
  '/sign-in' => [
    'title' => 'Sign in',
    'controller' => __DIR__ . '/../../controllers/auth/AuthController.php',
    'class' => 'AuthController',
    'method' => 'signIn',
    'view' => __DIR__ . '/../../views/pages/auth/sign-in.php',
    'layout' => 'auth',
    'methods' => ['GET', 'POST'],
    'roles' => ['guest'],
    'nav' => [
      'label' => 'Sign in',
      'icon' => 'sign-in',
      'show' => false,
    ],
  ],
  '/sign-out' => [
    'title' => 'Sign out',
    'controller' => __DIR__ . '/../../controllers/auth/AuthController.php',
    'class' => 'AuthController',
    'method' => 'signOut',
    'layout' => 'none',
    'methods' => ['POST'],
    'roles' => ['owner', 'staff'],
    'nav' => [
      'label' => 'Sign out',
      'icon' => 'sign-out',
      'show' => false,
    ],
  ],
  '/not-found' => [
    'title' => 'Not found',
    'view' => __DIR__ . '/../../views/pages/not-found.php',
    'layout' => 'auth',
    'methods' => ['GET'],
    'roles' => ['owner', 'staff', 'guest'],
    'status_code' => 404,
    'nav' => [
      'label' => 'Not found',
      'icon' => 'not-found',
      'show' => false,
    ],
  ],
];
